### ISSUE TITLE
General OpenID support

### ISSUE THREAD

**Issue by jasperweyne** [jasperweyne/helpless-kiwi#135]
Currently, only integration with Bunny is supported. This should be modifiable to use any OpenID Connect based system. Note that this requires the storage of claims within Kiwi, as opposed to the need-based retrieval right now.

**Comment by A-Daneel** [comment]
@jasperweyne Isn't this resolves with the latest release? (2021/06/18)

**Comment by jasperweyne** [comment]
Yup
