### ISSUE TITLE
Newlines in activity descriptions won't display.

### ISSUE THREAD

**Issue by roelhem** [jasperweyne/helpless-kiwi#150]
It is currently not possible to display activity descriptions with multiple lines. This feature would be quite handy when the description has multiple paragraphs or when it should contain a list.

**Easy solution**
I think that it will work when you add the "nl2br" a filter to the template field that shows the description.

In other words, change line 69  of file [templates/activity/show.html.twig](https://github.com/jasperweyne/helpless-kiwi/blob/develop/templates/activity/show.html.twig) from

```html
<p>{{ activity.description }}</p>
```

to

```html
<p>{{ activity.description | nl2br }}</p>
```

The documentation of this filter can be found [here](https://twig.symfony.com/doc/2.x/filters/nl2br.html).

**Preferred Solution**
It would be amazing if every activity has an optional long description that can be displayed on the activity page. This field can than be displayed on the Admin-page with a WYSIWYG-editor like [CKEditor](https://ckeditor.com).

When you display this field, you can use a filter like [sanitize_html](https://github.com/tgalopin/html-sanitizer-bundle) to ensure that XSS attacks are impossible.

**Comment by jasperweyne** [comment]
Currently, the description is designed to be a short description to give a general indication of the activity, similar to the description of for example a Facebook event. If multiple lines were introduced, I imagine this would lead to a different type of usage; a full description of the activity, with instructions to participants, full time tables, etc.

I do recognize the inconsistency in user experience when newline characters are dropped, so currently I feel like your described easy solution solves this.

Regarding your preferred solution, I feel like we should explore further (in a different issue) what use-cases this would fulfill before continuing on that road.
