### ISSUE TITLE
System doesn't notify you when wrong email is used at "forgot password"

### ISSUE THREAD

**Issue by Marijnvanrossum** [jasperweyne/helpless-kiwi#17]
There's also a typo in the sentence: "Insctructies"
![wachtwoord vergeten](https://user-images.githubusercontent.com/54626465/63852179-0190f580-c998-11e9-8863-985a1c6b02a2.png)

You might also want to replace it with a proper full sentence ;)

**Comment by jasperweyne** [comment]
This is correct behaviour: you don't want to expose if an e-mail address is stored in the database to any malicious users, that would open up a security hole. Typo has been noted tho!
