### ISSUE TITLE
New Activity Color field contains Null value

### ISSUE THREAD

**Issue by DavidckPixel** [jasperweyne/helpless-kiwi#172]
**Describe the bug**
When creating a new Activity, The Color field Contains a Null value in its choices array, so when the user does not select
a color, there is a database error since the field cannot contain null. The color field is also not required

**To Reproduce**
1. Go to Admin/Activity/new
2. Fill in all the required fields
3. Set the color field on nothing
4. Click on "Toevoegen"

**Expected behavior**
It should when left empty, either not allow the creation of the activity, or set it too some base value.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 86.0

**Additional context**
Issue was spotted in the DuplicationRemoval branch

**Comment by LauraMJH** [comment]
Has been solved in newest dev build
