### ISSUE TITLE
invalid redirect on unauthorized urls

### ISSUE THREAD

**Issue by A-Daneel** [jasperweyne/helpless-kiwi#177]
**Describe the bug**
If you try to access a page without having the proper authorization you won't get redirected to the login page.
Instead you'll get a 'page not accessible' with a poorly formatted url.

This has been noted on the all the `/admin/*` pages

**To Reproduce**
1. Make sure kiwi is running stand alone.
2. Make sure you aren't logged in.
3. Go to `localhost:8080/admin/`.
4. See error.

**Expected behavior**
A redirect to the login page.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - Version: 86

**Comment by jasperweyne** [comment]
Seems to be resolved in at least the latest version, closing
