### ISSUE TITLE
Input bars tend to get small when logging in

### ISSUE THREAD

**Issue by Marijnvanrossum** [jasperweyne/helpless-kiwi#19]
This only seems to happen when a username and/or password are remembered by the browser (Chrome) and the user puts in, or changes, a username or password
![small bar](https://user-images.githubusercontent.com/54626465/63852890-a3fda880-c999-11e9-9023-3445d19a8c5f.png)

**Comment by jasperweyne** [comment]
Fixed by 6b560a02, closing
