### ISSUE TITLE
500 error when registering for activity

### ISSUE THREAD

**Issue by DavidckPixel** [jasperweyne/helpless-kiwi#217]
**Describe the bug**
A 500 Internal server error when signing up for an activity. Although you get a 500 error, when going into a different tab and going to Kiwi and the activity again, it will display the normal behaviour. And u are signed up, eventho u get a 500

**To Reproduce**
1. Go to an activity you want to sign up for in kiwi
2. Click on register

**Expected behavior**
A green textbox would pop up, saying that i signed up correctly, and that my request was processed

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 92 - 64 bit

**Additional context**
It happened while signing up for a ViaKunst Activity: ViaBorrel: 'T Pandje edition 14/9. I was the 20th person to register for an activity with 22 spaces. There were no price options and the activity was free. It was still 2 days until the activity registration closed.

![error](https://user-images.githubusercontent.com/71597250/132985275-8ca09319-6de6-4b5a-bd2f-2f7146e626d4.png)

**Comment by jasperweyne** [comment]
Unfortunately, this bug is not reproducible. Therefore, closing this for now.
