### ISSUE TITLE
Onleesbaar geel vlak als de afbeelding niet werkt

### ISSUE THREAD

**Issue by KireNemook12** [jasperweyne/helpless-kiwi#222]
**Describe the bug**

Links boven zie ik iets dat er op wijst dat er een afbeelding zou moeten staan, nu staat er een geel vlak. met links onder witte letters. Wit op geel vind ik erg slecht leesbaar

**To Reproduce**
1. Ga naar Kiwi
2. Klik op Eten 4-10
3. Zie het gele vlak wat de volle breedte van mijn scherm inneemt

**Expected behavior**
Dat de afbeelding laad, of als die niet laad dat dan een andere kleur dan geel gebruikt wordt. Als de letters wit blijven, dan zou ik zwart doen. Of anders rood.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Versie 94.0.4606.61 (Officiële build) (64-bits)

**Comment by jasperweyne** [comment]
Aangezien het resultaat van (of gebrek aan) inladen van de afbeelding pas in de browser bekend is, is de enige manier om dit op te lossen middels javascript. Javascript is op dit moment zeer minimaal aanwezig in Kiwi en het is de wens om het aantal technologien te beperken, ten gunste van de onderhoudbaarheid.

Bovendien is het de bedoeling dat activiteiten altijd een afbeeldingen hebben, geen afbeelding invoeren is niet ondersteund gedrag. Vanwege de combinatie van beide redenen is dit daarom een wontfix.
