### ISSUE TITLE
code 500 wanneer ik een event wilde maken

### ISSUE THREAD

**Issue by KireNemook12** [jasperweyne/helpless-kiwi#228]
**Describe the bug**
Ik wou als bestuur een event maken voor de kerstactiviteiten op 22 december. 
Na het formulier ingevuld te hebben 

**To Reproduce**
1. Go to https://kiwi.particolarte.nl/ ingelogd als bestuur (mij in het bijzonder)
2. Click on bestuur
3. Click on Nieuwe Activiteit
3. Vul het formulier in zoals aan gegeven op de foto
4. klik op toevoegen
4.  The server returned a "500 internal server error"

**Expected behavior**
401, met een event aangemaakt

**Screenshots**
![image](https://user-images.githubusercontent.com/20819057/145093299-dc3ea690-482b-40be-b1c6-4367fe5736bd.png)

**Desktop (please complete the following information):**
 - OS: window 10
 - Browser chrome
 - Versie 96.0.4664.45 (Officiële build) (64-bits)

**Comment by A-Daneel** [comment]
From what I can see on the screenshot I assume you forgot to select a colour in the color field.
Regardless of this, more people spoke up about the lack of field validation.

The release of 2022-01-25 should have implemented the needed field validation for activity creation.
I'll be closing this issue, if for some reason your issue persists even after this update feel free to reopen it.
