### ISSUE TITLE
Consistancy within the reserve list and participation list

### ISSUE THREAD

**Issue by Qwarder** [jasperweyne/helpless-kiwi#240]
**Is your feature request related to a problem? Please describe.**
The users are divided over two different kinds of list, reserve list and participation list. Certain options such as comments are not available within the reserve list. Having the same features on both lists would be a welcome addition.

**Describe the solution you'd like**
Make both lists consistent with the same features

**Describe alternatives you've considered**
Use a function building the list and let only the table used be the difference.

**Comment by jasperweyne** [comment]
Please elaborate on the exact functionality difference that would be desired, as the only difference seems to be comments?

**Comment by jasperweyne** [comment]
Closing as no feedback was provided
