### ISSUE TITLE
Mobile bug, no indication where the reserve list starts.

### ISSUE THREAD

**Issue by Qwarder** [jasperweyne/helpless-kiwi#241]
**Describe the bug**
If you view an activity on mobile there is no indication whether the participation list transitions to the reserve list.

**To Reproduce**
1. Make an activity
2. Add users to participation list
3. Add users to reserve list
4. On mobile navigate to {kiwi site}/activity/{activity ID}
5. See error

**Expected behavior**
Expected is to have the interface of the desktop with "Reservelijst" indicating a transition between the two lists

**Screenshots**
![image](https://user-images.githubusercontent.com/16338590/151248555-aa43e1a2-7e78-46e5-acb5-1967dafe4e1b.png)
expected view

**Smartphone (please complete the following information):**
 - Device: IPhone 13
 - OS: iOS 15.1.1
 - Browser safari

**Additional context**
Know to fail on other mobile devices as well

**Comment by jasperweyne** [comment]
This has been fixed by #229
