### ISSUE TITLE
Editing Activity sets capacity to default

### ISSUE THREAD

**Issue by DavidckPixel** [jasperweyne/helpless-kiwi#244]
**Describe the bug**
When editing an activity, the capacity is set back to the generic 20 participants

**To Reproduce**
1. Make an activity with a capacity of 40
2. Edit the Activity, You will now see the capacity field at 20,
3. Save the changed, the capacity will now be 20

**Expected behavior**
Activity capacity shouldnt automaticly default to 20 when editing

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version --

**Comment by A-Daneel** [comment]
This issue should be resolved after the latest [hotfix](https://github.com/jasperweyne/helpless-kiwi/pull/247). If not please let us know and we'll reopen the issue.
