### ISSUE TITLE
New activity form should automatically create default price option

### ISSUE THREAD

**Issue by jasperweyne** [jasperweyne/helpless-kiwi#27]
Right now, this is an extra. manual, step. This could and should be inlined in the creation form

**Comment by A-Daneel** [comment]
I've been thinking about this issue. What exactly do you mean with a default option? Do you indent to have the same default price option for each activity without user input?

I think that it could be useful to just prompt the user for a price option (perhaps this was your original intent).

And while we are working at this part of the flow. I could  see the added benefit of allowing the user at that point to add multiple price options. This shouldn't be too much extra work compared to just prompting the user for a single price option.

Curious to hear your thoughts @jasperweyne
