### ISSUE TITLE
Mouse changes to hand when hovering over "aanmelden" button but doesn't change back to mouse

### ISSUE THREAD

**Issue by KimJoy2507** [jasperweyne/helpless-kiwi#309]
**Describe the bug**
Mouse cursor turns into a hand when hoveringover the 'aanmeld' button, but stays a hand even when not hovering over the subsequently appearing 'aanmeldopties'

**To Reproduce**
1. Log in to kiwi
2. Go to an activity with multiple 'aanmeldopties'
3. Hover over 'aanmelden'

The hand should turn back into an arrow when not on the actual 'aanmeld' buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/116755235/198114350-c426908b-6319-429c-be97-ee780dc93ccc.png)

**Comment by jasperweyne** [comment]
Resolved by latest release
