### ISSUE TITLE
Notice of new updates

### ISSUE THREAD

**Issue by jasperweyne** [jasperweyne/helpless-kiwi#350]
**Is your feature request related to a problem? Please describe.**
Currently, admins are only notified of new updates when they are (actively) looking at the Discord, or when they accidentally stumble upon the updater. This might lead to a situation where Kiwi inadvertently isn't being updated.

**Describe the solution you'd like**
I'd like to add a flash warning to the admin when a new release is available (only visible to users with ROLE_ADMIN) with a link to the updater.

**Comment by jasperweyne** [comment]
I feel like we need to have a visual reminder that's continuously visible and distracting, and therefore motivates the user to update, in that they would like to remove that message. The options you described here might be too easily disregarded standalone. A variation or a combination with some other measures might suffice though.

**Comment by A-Daneel** [comment]
I've taken a quick stab at it. It's far from a finished pr, but was curious what you thought.
I think this will be cleaner, and don't think we should aim in "annoying" our users to update.
