### ISSUE TITLE
Error on kiwi DB during creation.

### ISSUE THREAD

**Issue by mattijsgietman** [jasperweyne/helpless-kiwi#352]
**Describe the bug**

When I removed the kiwi DB from the phpmyadmin to create this DB again I got the following error (Note* I didn't get this error on an older version of kiwi):

> Migration 20221202230206 failed during Execution. Error An exception occurred while executing 'ALTER TABLE kiwi_relation DROP id, DROP parent_id, DROP description, CHANGE person_id person_id CHAR(36) NOT NULL COMMENT '(DC2Type:guid)'':
> 
> SQLSTATE[HY000]: General error: 1832 Cannot change column 'person_id': used in a foreign key constraint 'FK_31E0BAB217BBB47'
> 
> In AbstractMySQLDriver.php line 128:
> 
>   An exception occurred while executing 'ALTER TABLE kiwi_relation DROP id, DROP parent_id, DROP description, CHANGE
>   person_id person_id CHAR(36) NOT NULL COMMENT '(DC2Type:guid)'':
> 
>   SQLSTATE[HY000]: General error: 1832 Cannot change column 'person_id': used in a foreign key constraint 'FK_31E0BAB
>   217BBB47'
> 
> 
> In Exception.php line 18:
> 
>   SQLSTATE[HY000]: General error: 1832 Cannot change column 'person_id': used in a foreign key constraint 'FK_31E0BAB
>   217BBB47'
> 
> 
> In PDOConnection.php line 141:
> 
>   SQLSTATE[HY000]: General error: 1832 Cannot change column 'person_id': used in a foreign key constraint 'FK_31E0BAB
>   217BBB47'
> 
> 
> doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [--] [<version>]
> 
> Script php bin/console doctrine:migrations:migrate -n handling the db-rebuild event returned with error code 1
> Script @db-rebuild was called via db-rebuild-dev

**To Reproduce**
1. Be sure to be on the latest version of kiwi
2. Drop the DB from phpmyadmin
3. Try to recreate the DB with 'composer db-rebuild-dev'

**Expected behavior**
(Re)create the DB for kiwi and adding the Admin and normal user account

**Screenshots**

![image](https://user-images.githubusercontent.com/20533900/223244396-ffb2df75-204f-4a42-96c3-94f094209200.png)

.

**Comment by A-Daneel** [comment]
Just to confirm, this was on the develop branch? I can't seem to reproduce the issue on my machine. (`composer db-rebuild-dev` runs normally)

**Comment by mattijsgietman** [comment]
Hi @A-Daneel worked with @mkrugr on this. A fix can be found in PR: https://github.com/jasperweyne/helpless-kiwi/pull/355

**Comment by A-Daneel** [comment]
This should be solved by #358
