### ISSUE TITLE
Adding a new contact

### ISSUE THREAD

**Issue by chickenandcows** [jasperweyne/helpless-kiwi#396]
**Describe the bug**
When I tried to enter a contact into kiwi it gave an error code. 

**To Reproduce**
1. Go to 'administrator'
2. Click on 'accounts'
3. Click on 'new'
4. Enter a 'given name' and 'email'
5. Click on 'add'

**Expected behavior**
I expected to have that contact added 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Browser google chrome

**Comment by jasperweyne** [comment]
Thanks for the report! Family name and given name are required fields, but it seems that they're incorrectly not indicated as such
