### ISSUE TITLE
Can members be listed on the activities in the order of the dates?

### ISSUE THREAD

**Issue by dldhna** [jasperweyne/helpless-kiwi#48]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dldhna** [comment]
hey hoi,

Op dit moment staan leden in een niet logische volgorde op de lijst als ze zich aanmelden. Dit zorgt ervoor dat iedereen op een random plek komt te staan wat best rot is. Zou heel fijn zijn als mensen op alfabetische volgorde erin komen te staan of op wanneer ze zich hebben aangemeld voor een activiteit. Zo zie je niemand over het hoofd

**Comment by jasperweyne** [comment]
Allebei gefixt nu, alfabetisch op de main page en op volgorde van aanmelden in de admin!

Fixed by aec2cf8, closing
