### ISSUE TITLE
Is kiwi able to give a notification if someone signs out from an activity?

### ISSUE THREAD

**Issue by dldhna** [jasperweyne/helpless-kiwi#50]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dldhna** [comment]
hoi,

kan er een melding worden gegeven als iemand zich voor de deadline afmeld voor een activiteit zodat je niet de gehele lijst hoeft te doorzoeken als iemand zich heeft afgemeld?

**Comment by jasperweyne** [comment]
We hebben nu lijst van afmeldingen toegevoegd, hopelijk helpt dit!

Fixed by aec2cf8f, closing
