### ISSUE TITLE
Yarn install does not work for npm

### ISSUE THREAD

**Issue by mkrugr** [jasperweyne/helpless-kiwi#60]
For some reason this does not install npm correctly. 

You can use "npm install" to satisfy the dependancies of "yarn dev", as for some reason the npm.exe is useable via the yarn installation.

**Comment by mkrugr** [comment]
Do note that this was not a fresh installation of kiwi, as it had been used to run a testserver beforehand.

**Comment by jasperweyne** [comment]
This is correct behaviour, as npm is unsupported.
