### ISSUE TITLE
Person schemas

### ISSUE THREAD

**Issue by jasperweyne** [jasperweyne/helpless-kiwi#85]
**Is your feature request related to a problem? Please describe.**
Right now, all fields related to a person entity are hardcoded. For groups of recipients, this is already a problem, since they have a full name stored, instead of a seperate firstname and lastname. Moreover, this results in a rigid applications that's outphased quickly by solutions such as an Excel sheet, which is undesirable.

**Describe the solution you'd like**
I would like to replace the current Person fields by a (primairy) ID and a serialized Schema. The schema describes the required fields, and generates forms to create and edit Person instances. Additionally, a PersonData entity would hold a serialized value relating to a schema field.

**Comment by mkrugr** [comment]
Victory at last. Added in the person schema update.
