### ISSUE TITLE
Activity Capacity & Reserve Lists

### ISSUE THREAD

**Issue by jasperweyne** [jasperweyne/helpless-kiwi#86]
**Is your feature request related to a problem? Please describe.**
Activities sometimes have a maximum number of attendees, for example when a bus is booked and this bus has a maximum number of seats. Right now, organizers need to manually review the order in which attendees have enlisted for the activity and determine how to distribute the available spots. Moreover, it would be nice if users could register after the deadline, in case attendees deregister after the deadline and they would want to trade spots.

**Describe the solution you'd like**
I propose a reserve list index is added to each registration. When this value is null, the registration is marked as a full registration to the activity. Users can register for this list between the deadline and the time the activity ends, and admins can register users to this list manually before the deadline and after the activity has ended, resembling normal registrations. However, admin can reorder positions on the reserve list freely.

Admins can move users manually from the reserve list to the list of attendees, or can send an email to a reserve list registrant. This mail contains a link to register as attendee, which is stored in the database and can be disabled after the mail has been sent. The mail contains a link to remove oneself from the reserve list as well. When this link is pressed, a mail will be automatically sent to the next person on the reserve list.

For activities, optionally, a maximum number of attendees can be set. When a capacity is set and either there already are registrations on the reserve list, or the capacity of the activity is met, new registrants are placed on the reserve list. Registered users can deregister until the activity has ended.

**Describe alternatives you've considered**
A maximum number of attendees for a certain price option would be possible as well, however, this would complicate swapping with someone in the reserve list massively.

**Comment by mkrugr** [comment]
Updated some time ago.
