### ISSUE TITLE
Adding new user returns 500 internal server error

### ISSUE THREAD

**Issue by annaloos** [jasperweyne/helpless-kiwi#89]
**Describe the bug**
When you try to add a new user and click "toevoegen" after filling out all the required fields, you get this screen:
' Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.'

**To Reproduce**
1. Go to 'https://kiwi.viakunst-utrecht.nl/admin/person/'
2. Click on 'Nieuw'
3. Fill out all the fields
4. Click 'toevoegen'
5. See error

**Expected behavior**
Expected is that a new user is added.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Home
 - Browser: Chrome
 - Version Versie 78.0.3904.97

**Smartphone (please complete the following information):**
 - Device:  #LG-H870
 - OS: Android7.0
 - Browser: Chrome
 - Version 78.0.3904.96

**Additional context**

**Comment by jasperweyne** [comment]
Should be fixed by d9889322e399c5d233b09aa61281894476b91cee, thanks for the bug report!
