### ISSUE TITLE
Revealing failed login message

### ISSUE THREAD

**Issue by HugoPeters1024** [jasperweyne/helpless-kiwi#90]
**Describe the bug**
Attempting to login with a non existing username gives a different alert than logging in with an existing user but wrong password. This allows you to derive all user's email.

**Expected behavior**
Both cases should yield the exact same "Invalid Credentials" prompt.

**Comment by mkrugr** [comment]
Good suggestion, thank you.

**Comment by jasperweyne** [comment]
Fixed by ae496ed6
