### ISSUE TITLE
Adding participant to activity without available price options

### ISSUE THREAD

**Issue by SomeOrangeNebula** [jasperweyne/helpless-kiwi#91]
**Describe the bug**
Adding a participant to an activity that does not contain price options results in an exception.

**To Reproduce**
1. Create a new activity
2. Add a new participant to the activity (leave the option menu blank (it should not contain any options))
3. See bug

**Expected behavior**
Adding a participant to an activity that does not have price options should result in a pop up warning you about the problem and the program refusing to write in the participant.

**Comment by mkrugr** [comment]
Fixed by bugfix merge
